### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Misthalin** [ntnu-design/ntnu-avgangsutstilling-2023#25]

**Comment by Misthalin** [comment]
Lag komponenten med active class for å bytte ut farge basert på hvilken side,
ta kontakt med Henrik for å få linker til sosiale medier

![image](https://user-images.githubusercontent.com/72019688/224383819-458b49e6-1739-4362-833d-5058d8bd997f.png)

**Comment by Misthalin** [comment]
sivert

**Comment by kristwob** [comment]
Footer viser oransje på hver student, uavhengig av studieprogram
