### ISSUE TITLE
Create a temporary landing site which can be deployed until the site is finished

### ISSUE THREAD

**Issue by Misthalin** [ntnu-design/ntnu-avgangsutstilling-2023#5]
Should include links to social media and some short text about the exhibition.

**Comment by kristwob** [comment]
Check out this link for the figma prototype:
[https://www.figma.com/file/l5EiWyqB3IImWWZYEXz1gz/Hi-fi-prototype?node-id=0%3A1&t=GQfGPdMS5g13EV3t-1](url)
